export const pagesRoutes = [
  ["v-c0c85b84","/zh-cn/",{"y":"h","t":"主页","i":"home"},["/zh-cn/README.md"]],
  ["v-7c1ade66","/en-us/",{"y":"h","t":"Homepage","i":"home"},["/en-us/README.md"]],
  ["v-17f1319a","/zh-cn/elements/",{"y":"a","t":"构成 Lit 程序的元素"},["/zh-cn/elements/README.md"]],
  ["v-61e25fb8","/zh-cn/elements/literal.html",{"y":"a","t":"字面量"},[":md"]],
  ["v-9b16b9a4","/zh-cn/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/zh-cn/demo/README.md"]],
  ["v-a0b005c2","/zh-cn/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":4},[":md"]],
  ["v-763213c2","/zh-cn/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-1f1c37fe","/zh-cn/demo/layout.html",{"y":"a","t":"布局","i":"object-group","O":2},[":md"]],
  ["v-3a890e48","/zh-cn/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-ab879f88","/zh-cn/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":3},[":md"]],
  ["v-948919bc","/zh-cn/get-start/",{"y":"a","t":"写在前面"},["/zh-cn/get-start/README.md"]],
  ["v-86ef15a4","/zh-cn/get-start/env.html",{"y":"a","t":"环境准备","i":"dev"},[":md"]],
  ["v-bbc45f1e","/zh-cn/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/zh-cn/guide/README.md"]],
  ["v-e8821ff4","/en-us/demo/",{"y":"a","t":"Features demo","i":"laptop-code"},["/en-us/demo/README.md"]],
  ["v-0e6dc5f7","/en-us/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"gears","O":4},[":md"]],
  ["v-561046cc","/en-us/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},[":md"]],
  ["v-7fe3a029","/en-us/demo/layout.html",{"y":"a","t":"Layout","i":"object-group","O":2},[":md"]],
  ["v-5caecb04","/en-us/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"fab fa-markdown","O":2},[":md"]],
  ["v-e0825338","/en-us/demo/page.html",{"y":"a","t":"Page Config","i":"file","O":3},[":md"]],
  ["v-1bc5c2ce","/en-us/guide/",{"y":"a","t":"Guide","i":"lightbulb"},["/en-us/guide/README.md"]],
  ["v-75c79326","/zh-cn/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/zh-cn/guide/bar/README.md"]],
  ["v-1c01970b","/zh-cn/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-75c387cc","/zh-cn/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/zh-cn/guide/foo/README.md"]],
  ["v-0268d5ee","/zh-cn/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-4af83095","/en-us/guide/bar/",{"y":"a","t":"Bar feature","i":"lightbulb"},["/en-us/guide/bar/README.md"]],
  ["v-d4162d9a","/en-us/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-4afa3642","/en-us/guide/foo/",{"y":"a","t":"Foo feature","i":"lightbulb"},["/en-us/guide/foo/README.md"]],
  ["v-78bee731","/en-us/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
